"""
Autogenerated low-level API to all features of libxc
"""
module libxc
    using Libxc_jll
    const libxc = Libxc_jll.libxc

    include("gen/libxc.jl")
    include("gen/libxc_common.jl")

    # export everything
    foreach(names(@__MODULE__, all=true)) do s
        if startswith(string(s), "xc_") || startswith(string(s), "XC_")
            @eval export $s
        end
    end
end
